// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SB.Management.Infrastructure.Persistence;

#nullable disable

namespace SB.Management.Infrastructure.Migrations
{
    [DbContext(typeof(SbGestionPagosDbContext))]
    partial class SbGestionPagosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SB.Management.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroSeguroSocial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimerNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroSeguroSocial")
                        .IsUnique();

                    b.ToTable("Empleado", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleCalculo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("date");

                    b.Property<decimal>("MontoCalculado")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.EmpleadoAsalariado", b =>
                {
                    b.HasBaseType("SB.Management.Domain.Entities.Empleado");

                    b.Property<decimal>("SalarioSemanal")
                        .HasColumnType("decimal(12,2)");

                    b.ToTable("EmpleadoAsalariado", (string)null);
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.EmpleadoAsalariadoComision", b =>
                {
                    b.HasBaseType("SB.Management.Domain.Entities.Empleado");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TarifaComision")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("VentasBrutas")
                        .HasColumnType("decimal(14,2)");

                    b.ToTable("EmpleadoAsalariadoComision", (string)null);
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.EmpleadoPorComision", b =>
                {
                    b.HasBaseType("SB.Management.Domain.Entities.Empleado");

                    b.Property<decimal>("TarifaComision")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("VentasBrutas")
                        .HasColumnType("decimal(14,2)");

                    b.ToTable("EmpleadoPorComision", (string)null);
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.EmpleadoPorHora", b =>
                {
                    b.HasBaseType("SB.Management.Domain.Entities.Empleado");

                    b.Property<decimal>("HorasTrabajadas")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("SueldoPorHora")
                        .HasColumnType("decimal(12,2)");

                    b.ToTable("EmpleadoPorHora", (string)null);
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.Pago", b =>
                {
                    b.HasOne("SB.Management.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Pagos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SB.Management.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.EmpleadoAsalariado", b =>
                {
                    b.HasOne("SB.Management.Domain.Entities.Empleado", null)
                        .WithOne()
                        .HasForeignKey("SB.Management.Domain.Entities.EmpleadoAsalariado", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.EmpleadoAsalariadoComision", b =>
                {
                    b.HasOne("SB.Management.Domain.Entities.Empleado", null)
                        .WithOne()
                        .HasForeignKey("SB.Management.Domain.Entities.EmpleadoAsalariadoComision", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.EmpleadoPorComision", b =>
                {
                    b.HasOne("SB.Management.Domain.Entities.Empleado", null)
                        .WithOne()
                        .HasForeignKey("SB.Management.Domain.Entities.EmpleadoPorComision", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.EmpleadoPorHora", b =>
                {
                    b.HasOne("SB.Management.Domain.Entities.Empleado", null)
                        .WithOne()
                        .HasForeignKey("SB.Management.Domain.Entities.EmpleadoPorHora", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SB.Management.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
